image: fedora:latest

generaltester:
  script:
  - dnf install -y graphviz python3-pip python3-devel gcc cargo rustfmt diffutils ncurses gdb
  - pip3 install python-Levenshtein
  - bash grade.sh
  timeout: 2 hours 30 minutes
  artifacts:
    when: always
    paths:
      - results.txt
    expire_in: 1 month
